---

- name: add apt repo for nginx with pagespeed
  apt_repository: repo='ppa:adegtyarev/nginx-pagespeed'
  register: apt_repo

- name: apt-get update if we updated the apt-repo
  apt: update_cache=True
  when: apt_repo|changed
