---
# handlers file for ansible-nginx

- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes

- name: start nginx
  service: name=nginx state=started
  sudo: yes

- name: stop nginx
  service: name=nginx state=stopped
  sudo: yes
